import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:5173/');
  await page.getByLabel('Featured Photography').getByRole('link', { name: 'Book a Session' }).click();
  await page.getByRole('button', { name: 'Inquire Now' }).first().click();
  await page.getByRole('textbox', { name: 'Name *' }).fill('Siddhant Kore');
  await page.getByRole('textbox', { name: 'Email *' }).click();
  await page.getByRole('textbox', { name: 'Email *' }).fill('siddhskore@gmail.com');
  await page.getByRole('textbox', { name: 'Phone' }).click();
  await page.getByRole('textbox', { name: 'Phone' }).fill('9309752177');
  await page.getByRole('textbox', { name: 'Message *' }).click();
  await page.getByRole('textbox', { name: 'Message *' }).fill('We want to inquire about kids photography');
  await page.getByRole('button', { name: 'Submit Inquiry' }).click();
  await page.locator('#radix-_r_0_').click();
  await page.locator('html').click();
  await page.getByRole('link', { name: 'Commercial Shoots Brand-' }).click();
  await page.getByLabel('Call to action').getByRole('link', { name: 'Book a Session' }).click();
  await page.getByLabel('Most Popular').getByRole('link', { name: 'View All →' }).click();
  await page.getByRole('link', { name: 'Animal Animal 5 items' }).click();
  await page.getByText('WildLife (1)').click();
  await page.getByRole('checkbox', { name: 'Animal (5)' }).click();
  await page.getByRole('checkbox', { name: 'Nature (5)' }).click();
  await page.getByRole('checkbox', { name: 'WildLife (1)' }).click();
  await page.getByRole('checkbox', { name: 'Baby (1)' }).click();
  await page.getByText('CategoriesNature (5)WildLife').click();
  await page.getByRole('checkbox', { name: 'photo' }).click();
  await page.getByRole('checkbox', { name: 'Baby (1)' }).click();
  await page.getByRole('checkbox', { name: 'bundle' }).click();
  await page.getByRole('checkbox', { name: 'photo' }).click();
  await page.getByRole('button', { name: 'Clear all filters' }).click();
  await page.getByText('square').click();
  await page.getByRole('checkbox', { name: 'landscape' }).click();
  await page.getByRole('slider', { name: 'Minimum' }).click();
  await page.locator('.bg-primary').first().click();
  await page.getByRole('button', { name: 'Clear all filters' }).click();
  await page.getByRole('link', { name: 'Baby Photo photo Baby Photo' }).click();
  await page.getByText('Full HD1920 x 1080₹').click();
  await page.getByText('4K3840 x 2160₹').click();
  await page.getByRole('button', { name: 'Add to Cart' }).click();
  await page.getByRole('button', { name: 'Services' }).click();
  await page.getByRole('button', { name: 'Explore' }).click();
  await page.getByRole('link', { name: 'Like Photo Studio logo Like' }).click();
  await page.getByLabel('Latest Uploads').getByRole('link', { name: 'View All →' }).click();
  await page.getByRole('button', { name: 'View All' }).first().click();
  await page.getByRole('button', { name: 'Blog' }).click();
  await page.getByRole('link').filter({ hasText: 'babybabyphotographyBlog2How' }).click();
  await page.getByRole('button', { name: 'Back to Blog' }).click();
  await page.getByRole('link').filter({ hasText: 'Blog 1How to Make Effective' }).click();
  await page.getByRole('button', { name: 'Back to Blog' }).click();
  await page.locator('#radix-_r_0_').click();
  await page.getByRole('menuitem', { name: 'Log in' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('megastorage2112@gmail.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Siddhant@123');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('button', { name: '1' }).click();
  await page.getByRole('button', { name: 'Remove' }).click();
  await page.getByRole('button', { name: 'Explore' }).click();
  await page.getByRole('button', { name: 'View All' }).nth(2).click();
  await page.getByRole('link', { name: 'Small Beautiful Butterfly' }).click();
  await page.getByText('4K3840 x 2160₹99₹12923% off').click();
  await page.getByRole('button', { name: 'Add to Cart' }).click();
  await page.getByRole('link', { name: 'Beautiful Butterfly photo' }).click();
  await page.getByText('HD1280 x 720₹').click();
  await page.getByRole('button', { name: 'Add to Cart' }).click();
  await page.getByRole('link', { name: 'Small Beautiful Butterfly' }).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('button', { name: 'Share' }).click();
  await page.getByRole('button').nth(3).click();
  await page.getByRole('button', { name: '2' }).click();
  await page.locator('#radix-_r_0_').click();
  await page.locator('html').click();
  await page.getByRole('button', { name: 'Proceed to Checkout' }).click();
  await page.getByRole('button', { name: 'Pay ₹' }).click();
  await page.locator('iframe').contentFrame().getByTestId('contact-overlay-container').getByRole('button').filter({ hasText: /^$/ }).click();
  await page.locator('iframe').contentFrame().getByTestId('confirm-positive').click();
  await page.locator('#radix-_r_0_').click();
  await page.getByRole('menuitem', { name: 'Logout' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('admin@gmail.com');
  await page.getByRole('textbox', { name: 'Email' }).press('Tab');
  await page.getByRole('textbox', { name: 'Password' }).fill('admin123');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByText('ExploreServicesBlog1').click();
  await page.getByRole('button', { name: '1' }).click();
  await page.getByRole('button', { name: 'Remove' }).click();
  await page.locator('#radix-_r_0_').click();
  await page.getByRole('menuitem', { name: 'Admin Dashboard' }).click();
  await page.getByRole('link', { name: 'Products' }).click();
  await page.getByRole('button', { name: 'Mark' }).first().click();
  await page.getByRole('button').nth(3).click();
  await page.getByRole('spinbutton', { name: 'Full HD Actual Price (₹)' }).click();
  await page.getByRole('spinbutton', { name: 'Full HD Actual Price (₹)' }).fill('29');
  await page.getByRole('combobox').filter({ hasText: 'Yes' }).click();
  await page.getByRole('option', { name: 'No' }).click();
  await page.getByRole('combobox').filter({ hasText: 'Active' }).click();
  await page.getByLabel('Inactive').getByText('Inactive').click();
  await page.getByRole('button', { name: 'Update Product' }).click();
  await page.getByRole('combobox').filter({ hasText: 'All products' }).click();
  await page.getByLabel('All products').getByText('All products').click();
  await page.getByRole('link', { name: 'Categories' }).click();
  await page.getByRole('button').nth(4).click();
  await page.getByRole('textbox', { name: 'Image URL' }).click();
  await page.getByRole('textbox', { name: 'Image URL' }).click();
  await page.getByRole('textbox', { name: 'Image URL' }).dblclick();
  await page.getByRole('textbox', { name: 'Image URL' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Image URL' }).press('ControlOrMeta+c');
  await page.getByRole('textbox', { name: 'Image URL' }).fill('https://www.pexels.com/photo/smiling-baby-lying-on-soft-blanket-indoors-35759297/');
  await page.getByRole('textbox', { name: 'Image URL' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Image URL' }).fill('https://www.pexels.com/photo/smiling-baby-lying-on-soft-blanket-indoors-35759297/');
  await page.getByRole('button', { name: 'Update Category' }).click();
  await page.locator('tr:nth-child(4) > td:nth-child(5) > .flex > .inline-flex.items-center.justify-center.whitespace-nowrap.text-sm.font-medium.transition-all.disabled\\:pointer-events-none.disabled\\:opacity-50.\\[\\&_svg\\]\\:pointer-events-none.\\[\\&_svg\\:not\\(\\[class\\*\\=\\\'size-\\\'\\]\\)\\]\\:size-4.shrink-0.\\[\\&_svg\\]\\:shrink-0.outline-none.focus-visible\\:border-ring.focus-visible\\:ring-ring\\/50.focus-visible\\:ring-\\[3px\\].aria-invalid\\:ring-destructive\\/20.dark\\:aria-invalid\\:ring-destructive\\/40.aria-invalid\\:border-destructive.hover\\:bg-accent.hover\\:text-accent-foreground').click();
  await page.getByRole('combobox').click();
  await page.getByLabel('Inactive').getByText('Inactive').click();
  await page.getByRole('button', { name: 'Update Category' }).click();
  await page.getByRole('link', { name: 'Services' }).click();
  await page.getByRole('button', { name: 'Add Service' }).click();
  await page.getByRole('textbox', { name: 'Title *' }).fill('Business Shoot');
  await page.getByRole('textbox', { name: 'Description *' }).click();
  await page.getByRole('textbox', { name: 'Description *' }).fill('hjdajhkjskwodi aksowfhn,mcbu');
  await page.getByRole('textbox', { name: 'Description *' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Description *' }).press('ControlOrMeta+c');
  await page.getByRole('textbox', { name: 'Description *' }).press('ControlOrMeta+c');
  await page.getByRole('textbox', { name: 'Description *' }).fill(' hjdajhkjskwodi aksowfhn,mcbu hjdajhkjskwodi aksowfhn,mcbu hjdajhkjskwodi aksowfhn,mcbu,. hjdajhkjskwodi aksowfhn,mcbu,kajh');
  await page.getByRole('textbox', { name: 'Description *' }).press('ControlOrMeta+Unidentified');
  await page.getByRole('textbox', { name: 'Description *' }).fill(' hjdajhkjskwodi aksowfhn,mcbu hjdajhkjskwodi aksowfhn,mcbu hjdajhkjskwodi aksowfhn,mcbu,. hjdajhkjskwodi aksowfhn,mcbu,kajhhjdajhkjskwodi aksowfhn,mcbu');
  await page.getByRole('combobox').filter({ hasText: 'Camera' }).click();
  await page.getByRole('combobox').filter({ hasText: 'Camera' }).click();
  await page.getByRole('combobox').filter({ hasText: 'Camera' }).click();
  await page.getByRole('textbox', { name: 'Price' }).click();
  await page.getByRole('textbox', { name: 'Price' }).fill('1999');
  await page.getByRole('combobox').filter({ hasText: 'Camera' }).click();
  await page.getByRole('combobox').filter({ hasText: 'Camera' }).click();
  await page.getByRole('textbox', { name: 'Feature' }).click();
  await page.getByRole('textbox', { name: 'Feature' }).fill('Feature 1');
  await page.getByRole('button', { name: 'Add Feature' }).click();
  await page.getByRole('textbox', { name: 'Feature' }).nth(1).click();
  await page.getByRole('textbox', { name: 'Feature' }).nth(1).fill('Feature 2');
  await page.getByRole('button', { name: 'Add Feature' }).click();
  await page.getByRole('textbox', { name: 'Feature' }).nth(2).click();
  await page.getByRole('textbox', { name: 'Feature' }).nth(2).fill('Feature 3');
  await page.getByRole('textbox', { name: 'Image URL' }).click();
  await page.getByRole('textbox', { name: 'Image URL' }).fill('https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ1-Osxu4BzFuq2Gc_X8pkaC0EGtdM7X981ww&s');
  await page.getByRole('spinbutton', { name: 'Order' }).dblclick();
  await page.getByRole('spinbutton', { name: 'Order' }).fill('30');
  await page.getByLabel('Add Service').getByText('Order').click();
  await page.getByRole('spinbutton', { name: 'Order' }).fill('40');
  await page.getByRole('spinbutton', { name: 'Order' }).click();
  await page.getByRole('spinbutton', { name: 'Order' }).press('ArrowLeft');
  await page.getByRole('spinbutton', { name: 'Order' }).fill('30');
  await page.getByRole('combobox').filter({ hasText: 'Camera' }).click();
  await page.getByRole('combobox').filter({ hasText: 'Camera' }).click();
  await page.getByRole('combobox').filter({ hasText: 'Camera' }).click();
  await page.getByRole('combobox').filter({ hasText: 'Camera' }).click();
  await page.getByRole('button', { name: 'Create Service' }).click();
  await page.getByRole('link', { name: 'Users' }).click();
  await page1.goto('http://localhost:5173/login');
  await page.getByRole('link', { name: 'Users' }).click();
  await page2.goto('http://localhost:5173/login');
  await page.getByRole('link', { name: 'Orders' }).click();
  await page3.goto('http://localhost:5173/login');
  await page.goto('http://localhost:5173/');
  await page.locator('#radix-_r_0_').click();
  await page.locator('#radix-_r_0_').click();
  await page.locator('#radix-_r_0_').click();
  await page.locator('#radix-_r_0_').click();
  await page.goto('http://localhost:5173/login');
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.locator('#radix-_r_0_').click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('admin@gmail.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('admin123');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.locator('#radix-_r_0_').click();
  await page.locator('#radix-_r_0_').click();
  await page.getByRole('button').nth(4).click();
  await page4.goto('http://localhost:5173/cart');
  await page4.getByRole('link', { name: 'Products' }).click();
  await page4.goto('http://localhost:5173/');
  await page4.getByRole('button', { name: 'Explore' }).click();
  await page4.getByRole('link', { name: 'Baby Photo photo Baby Photo' }).first().click();
  await page4.getByText('HD1280 x 720₹1Full HD1920 x').click();
  await page4.getByRole('button', { name: 'Add to Cart' }).click();
  await page4.locator('#radix-_r_0_').click();
  await page4.getByRole('menuitem', { name: 'Logout' }).click();
  await page4.locator('#radix-_r_0_').click();
  await page4.getByRole('menuitem', { name: 'Log in' }).click();
  await page4.getByRole('textbox', { name: 'Email' }).click();
  await page4.getByRole('textbox', { name: 'Email' }).fill('admin@gmail.com');
  await page4.getByRole('textbox', { name: 'Password' }).click();
  await page4.getByRole('textbox', { name: 'Password' }).fill('admin123');
  await page4.getByRole('button', { name: 'Login' }).click();
  await page4.locator('#radix-_r_0_').click();
  await page4.getByRole('menuitem', { name: 'Admin Dashboard' }).click();
  await page4.getByRole('button', { name: 'Explore' }).click();
  await page4.getByRole('link', { name: 'Baby Photo photo Baby Photo' }).first().click();
  await page4.getByRole('button', { name: 'Add to Cart' }).click();
  await page4.locator('#radix-_r_h_').click();
  await page4.getByRole('menuitem', { name: 'Admin Dashboard' }).click();
  await page4.getByRole('link', { name: 'Products' }).click();
  await page4.getByText('inactive').click();
  page4.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page4.getByRole('button').nth(4).click();
  await page4.getByRole('button').nth(3).click();
  await page4.getByRole('combobox').filter({ hasText: 'Inactive' }).click();
  await page4.getByLabel('Active', { exact: true }).getByText('Active').click();
  await page4.getByRole('button', { name: 'Update Product' }).click();
  page4.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page4.getByRole('button').nth(4).click();
  await page4.getByRole('cell', { name: 'Mark' }).first().click();
  await page4.getByRole('link', { name: 'Categories' }).click();
  await page4.locator('tr:nth-child(4) > td:nth-child(5) > .flex > .inline-flex.items-center.justify-center.whitespace-nowrap.text-sm.font-medium.transition-all.disabled\\:pointer-events-none.disabled\\:opacity-50.\\[\\&_svg\\]\\:pointer-events-none.\\[\\&_svg\\:not\\(\\[class\\*\\=\\\'size-\\\'\\]\\)\\]\\:size-4.shrink-0.\\[\\&_svg\\]\\:shrink-0.outline-none.focus-visible\\:border-ring.focus-visible\\:ring-ring\\/50.focus-visible\\:ring-\\[3px\\].aria-invalid\\:ring-destructive\\/20.dark\\:aria-invalid\\:ring-destructive\\/40.aria-invalid\\:border-destructive.hover\\:bg-accent.hover\\:text-accent-foreground').click();
  await page4.getByRole('combobox').click();
  await page4.getByRole('option', { name: 'Active', exact: true }).click();
  await page4.getByRole('button', { name: 'Update Category' }).click();
  await page4.getByRole('link', { name: 'Services' }).click();
  await page4.getByRole('link', { name: 'Users' }).click();
  await page4.getByRole('link', { name: 'Orders' }).click();
  await page4.getByRole('link', { name: 'Blogs' }).click();
  await page4.getByRole('link', { name: 'Advertisements' }).click();
  await page4.getByRole('link', { name: 'Inquiries' }).click();
  await page4.getByRole('link', { name: 'Inquiries' }).click();
  await page4.getByRole('button').nth(1).click();
  await page4.getByRole('textbox', { name: 'Admin Tag (one word)' }).click();
  await page4.getByRole('textbox', { name: 'Admin Tag (one word)' }).fill('Pendign');
  await page4.getByRole('combobox').click();
  await page4.getByRole('option', { name: 'COMPLETED' }).click();
});